### PR TITLE
Dynamic headtags server-rendered for social sharing

### LINKED ISSUE #3: Add social media preview function
So that when people post a code tour on Twitter, they get a preview card. Those definitely get more clicks than a plain link.

The preview card should have:
1. Target repo
2. Target repo avatar
3. Author name
4. Description

### PR DESCRIPTION
**Pull request by xavxyz**
Hey!

What's up?
---
PR to fix #3 🏝

It uses `react-helmet` coupled with `WebApp.connectHandlers` so a server/bot requesting a page get the relevant head tags: generic meta or tour-related meta 👍 

Link tags & `ga` are still hard coded; I don't believe there is a real benefit of generating them automatically unless we totally get rid of `main.html`.

I've created a `Headtags` component that is also reused on the client.

Screenshot from a local `curl`:
successful curl

We get the meta needed for a Twitter card! 🎉 

What could be next?
---
I believe this simple SSR thing opens the door for rendering all components (accessible now on both env from `/components` folder) with data server-side 🌮 
However, we depend on `Meteor.subscribe` at the moment which is not defined server-side. 

I'm not eager to use [fast-render](https://github.com/kadirahq/fast-render), so what about refactoring the code to use Apollo? 

That would be also a good call to refactor components (simpler components, consistent styling, extracting some helpers that are used in many places as class methods, ...)? I'm totally in to do a PR for that if you think that could be useful 👌 

some parrot

### CODE REVIEW

**Comment by stubailo** [comment]
> what about refactoring the code to use Apollo?

Oh yes! I definitely want to do that.

Definitely open to any PRs to make the code simpler as well!

What would you prefer to work on, and what should I tackle?

**Comment by stubailo** [comment]
This looks great!

**Comment by stubailo** [comment]
Check out out!

screenshot 2017-03-11 23 49 16

**Comment by xavxyz** [comment]
Yay, awesome!! 🎉

Both working on implementing Apollo tools and having simpler components are appealing 😁 

I'm eager to start with some work on the components. I used `styled-components` recently, the dev experience has been great:  I'm thinking​ about using them here!

On the data side, do we keep the same data model to base our schema on? There may be room to leverage the GitHub GraphQL API? 🤔🚀 Do you want to work on setting the server / schema / resolvers?

**Pull request merged**
