### PR TITLE
Principled approach for loading / not found states

### PR DESCRIPTION
**Pull request by xavxyz**
Hey! 👋 

Quoting from #4 -  "Fix data loading bugs": 

> We need to adopt a principled approach for this.

Thanks to `recompose`, I've been composing & `branch`ing on the different containers:
1. Load meteor data (handle `tours` (and `steps` if needed) subscriptions directly in the container
2. Show loading component if subscriptions aren't ready
3. Show not found component if no data found for the query

This avoids React to fail badly. 

I believe it's a first step toward a better code tour experience. There is still room for a lot of improvement (do not subscribe to all tours, more statuses depending on what is loading (tour/step), transitions between states).

**Funky part:**

Loading & not found component are based on a... party parrot! party parrot! 🎉  (let's be consistent 🤔 )

Here are GIF recording of GIFs ( hum 💭  ):

loading

not found

### CODE REVIEW

**Comment by stubailo** [comment]
Wow amazing! Just saw this PR, taking a look now.

**Comment by stubailo** [comment]
Incredible, awesome change :]

**Comment by stubailo** [comment]
Upgraded to newest Meteor, redeploying now.

**Comment by Slava** [comment]
lmao

**Pull request merged**
